#pragma once

#define MASTER_LEFT

#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_SLEEP

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR

#define DEBOUNCE 5

#define TAPPING_TERM 180
#define PERMISSIVE_HOLD

#define COMBO_COUNT 0

#define OLED_TIMEOUT 60000

#define FORCE_NKRO

#define FAST_OCTOPUS