VIA_ENABLE = no
LTO_ENABLE = yes

SPLIT_KEYBOARD = yes

MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

ENCODER_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = lite

WPM_ENABLE = yes
OLED_ENABLE = yes